In [ ]:
import module
import pandas as pd
# df_kline = pd.read_csv("static/SAMPLE/kline/kline5m_48h.csv")

Symbol = "BTCUSDT"
days = 3
result_type = "test"

df_kline = module.create_df_origin(Symbol, days)

df_bt_result = pd.DataFrame({\
    'PARAMS_SERIES':[[100,50, 60],[100,50, 60],[]],\
    'UNFINISHED_PROFIT':[0.12,0.12,0],\
    'NET_PROFIT_SERIES':[[3.23, -1.32, 2.11], [-2.23, 1.32, -3.11],[]],\
    'PAPER_LOSS_SERIES':[[-1.45, -2.34, -1.22], [-2.45, -4.34, -6.22],[]],\
    'ENTRY_TIME_SERIES':[[1670770095,1670770095,1670770095],[1670771095,1670771095,1670771095],[]],\
    'EXIT_TIME_SERIES':[[1670784695,1670979795,1670999095],[1670987695,1671979695,1671001095],[]]})

print(df_bt_result)

df_bt_result = module.calc_result(df_kline, df_bt_result, Symbol, "Strategy", days, result_type, chunk_div_size = 0, chunk_index = 0)
df_bt_result.to_csv(f"test/testfile.csv")
print(df_bt_result)

In [4]:
import module

df_elite_all = pd.read_csv("/home/viceversa/Dropbox/bankof3v/static/GBTA/DEBUG/2212180208/elite.csv")
df_TestRun_all = pd.read_csv("/home/viceversa/Dropbox/bankof3v/static/GBTA/DEBUG/2212180208/testrun.csv")

df_performance = module.calc_performance(df_elite_all, df_TestRun_all)

print(df_performance)

   TIME_EFFICIENCY
0             -0.0
1              0.0
2              0.0
3              0.0
4             -0.0
5              0.0

In [2]:

import module
Symbol = 'BTCUSDT'
TimeFrame = 1
days = 3
df_kline = module.create_df_kline(Symbol, TimeFrame, days)
df_kline

2022-12-19 12:28:21,977 : Fetching data for __BTCUSDT__ for 3 days from Binance.

          OpenTime      High       Low     Close   Volume
0     1.671161e+09  17396.00  17393.30  17393.30   54.489
1     1.671161e+09  17395.40  17392.10  17394.70  102.718
2     1.671161e+09  17394.70  17394.30  17394.40   25.607
3     1.671162e+09  17396.40  17393.60  17396.40   52.458
4     1.671162e+09  17396.40  17395.00  17395.00   33.089
...            ...       ...       ...       ...      ...
4315  1.671420e+09  16666.90  16664.00  16666.50  119.355
4316  1.671420e+09  16670.30  16663.80  16670.20  113.600
4317  1.671420e+09  16673.00  16670.20  16673.00   73.797
4318  1.671420e+09  16679.40  16673.00  16678.60  142.235
4319  1.671420e+09  16678.60  16673.70  16673.70   86.158

[4320 rows x 5 columns]